### ISSUE TITLE
Case-insensitive substring matching

### ISSUE THREAD

**Issue by kunklejr** [pfmooney/node-ldap-filter#9]
The substring matching filter currently does case-sensitive matching, which is not what I'd normally expect. If that's not intentional, I believe it could be made insensitive by adding a second argument of "i" to the creation of the `RegEx` object on the line https://github.com/pfmooney/node-ldap-filter/blob/master/lib/substr_filter.js#L88

I'd be happy to submit a PR for this change as I need insensitive matching behavior. Please let me know if you'd like me to do so.

**Comment by pfmooney** [comment]
Absent some authoritative documentation to the contrary (such as an RFC), the matching behavior for SubtringFilter is operating as desired.  If a consumer wishes to loosen the expectations for case-sensitivity, they are free to do so by overriding the `matches()` method.

Thanks
